services:
  taisa-tablero:
    image: ghcr.io/sacon217/taisa-tablero:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taisa-tablero
    restart: unless-stopped
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "8010:8000"
