services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    networks:
      - bridge
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}