services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    networks:
      - bridge
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
    environment:
      - N8N_HOST=${HOST}
      - N8N_PORT=${PORT}
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://${HOST}/
      - GENERIC_TIMEZONE=America/Costa_Rica
    volumes:
      - /opt/n8n/data:/home/node/.n8n