networks:
  n8n_network:
    driver: bridge
    name: n8n_network

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    networks:
      - n8n_network
    extra_hosts:
      - "gmail.googleapis.com:142.251.34.138"
    ports:
      - "0.0.0.0:${PORT1}:${PORT1}"
    environment:
      - N8N_HOST=${HOST}
      - N8N_PORT=${PORT1}
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://${HOST}/
      - GENERIC_TIMEZONE=America/Costa_Rica
      - CODE_ENABLE_STDOUT=true
      - N8N_EDITOR_BASE_URL=https://${HOST}
      - N8N_BETA_FEATURES_ENABLED=1
      - N8N_MCP_ACCESS_ENABLED=true
    volumes:
      - /opt/n8n/data:/home/node/.n8n
      
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    networks:
      - n8n_network
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN} 
