networks:
  n8n_network:
    external: true

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    networks:
      - n8n_network
    ports:
      - "0.0.0.0:${PORT1}:${PORT1}"
      - "0.0.0.0:${PORT2}:${PORT2}"
    environment:
      - N8N_HOST=${HOST}
      - N8N_PORT=${PORT1}
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://${HOST}/
      - GENERIC_TIMEZONE=America/Costa_Rica
      - N8N_EDITOR_BASE_URL=https://${HOST}
      - N8N_RUNNERS_BROKER_LISTEN_ADDRESS=0.0.0.0
      - NODE_FUNCTION_ALLOW_EXTERNAL=re,os,json,math
      - N8N_RUNNERS_ENABLED=true
      - N8N_RUNNERS_MODE=external
      - N8N_RUNNERS_AUTH_TOKEN=${RUNNER_AUTH_TOKEN}
    volumes:
      - /opt/n8n/data:/home/node/.n8n
      
  n8n-task-runner:
    image: n8nio/runners:latest
    container_name: n8n-task-runner
    restart: unless-stopped
    networks:
      - n8n_network
    environment:
      - N8N_RUNNERS_AUTH_TOKEN=${RUNNER_AUTH_TOKEN}
      - N8N_RUNNERS_TASK_BROKER_URI=http://n8n:${PORT2}
