services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    networks:
      - home-lab-network
    environment:
      APP_URL: ${BESZEL_HUB}
    ports:
      - 8090:8090
    volumes:
      - ./beszel_data:/beszel_data
      - ./beszel_socket:/beszel_socket
    healthcheck:
      test: ['CMD', '/beszel', 'health', '--url', '${BESZEL_HUB}']
      interval: 120s
      start_period: 10s
      timeout: 5s

networks:
  home-lab-network:
    external: true
    name: home-lab-services_edge